// <auto-generated />
using DataScraper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataScraper.Migrations
{
    [DbContext(typeof(DataScrapContext))]
    [Migration("20230910072322_datascrapdb")]
    partial class datascrapdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataScraper.moviedata", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("imgurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("views")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("moviedata");
                });

            modelBuilder.Entity("DataScraper.movielink", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("fsize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leech")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("magnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("movielink");
                });
#pragma warning restore 612, 618
        }
    }
}
